### PR TITLE
Improved ESP32 + DHT11 sketch

### PR DESCRIPTION
**Pull request by ChromeUniverse**
Changes described in commit

### CODE REVIEW

**Comment by danielalexis** [comment]
Looks good to me! @Luberr-Dhruv and @Michael2MacDonald  will have also to approve

**Review by danielalexis — APPROVED** [review]
Seems good to me

**Comment by dhruvsujatha** [comment]
Looking at the changes and trying to catch if there are errors. @ChromeUniverse Did you check if the code worked with your ESP32?

**Comment by ChromeUniverse** [comment]
Yep, works for me (minus the DHT stuff, didn't change anything there)

**Review by dhruvsujatha — APPROVED** [review]
Looks Good! Those Comments really clear things up.

**Comment by dhruvsujatha** [comment]
I have gone over the edits twice now. Seems good to me. @Michael2MacDonald Your call.

**Review by Michael2MacDonald — APPROVED** [review]

**Pull request merged**
